### PR TITLE
Use futurize to have python 3 compatible print with import

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by persianpros** [comment]
@WanWizard please merge for py3

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-AutoBackup/tree/python3

**Comment by jbleyel** [comment]
HI @persianpros, don't change the master branch if there is a python3 branch.

**Comment by persianpros** [comment]
Sorry I didn't check and as these are both py versions compatible I sent the PRs

**Comment by jbleyel** [comment]
The master is for py2 and python3 branch is only tested on python3.

**Pull request closed without merging**
